version: '3.9'
services:
  vityaz-game:
    build: .
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3000
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
